apiVersion: apps/v1
kind: Deployment
metadata:
  name: seovalidator-app
  namespace: seovalidator
  labels:
    app: seovalidator
    component: app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: seovalidator
      component: app
  template:
    metadata:
      labels:
        app: seovalidator
        component: app
    spec:
      containers:
      - name: app
        image: seovalidator:latest
        ports:
        - containerPort: 9000
        envFrom:
        - configMapRef:
            name: seovalidator-config
        - secretRef:
            name: seovalidator-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /live
            port: 9000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 9000
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: storage
          mountPath: /var/www/html/storage
        - name: logs
          mountPath: /var/www/html/storage/logs
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: seovalidator-storage-pvc
      - name: logs
        persistentVolumeClaim:
          claimName: seovalidator-logs-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seovalidator-nginx
  namespace: seovalidator
  labels:
    app: seovalidator
    component: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: seovalidator
      component: nginx
  template:
    metadata:
      labels:
        app: seovalidator
        component: nginx
    spec:
      containers:
      - name: nginx
        image: seovalidator-nginx:latest
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: storage
          mountPath: /var/www/html/storage
          readOnly: true
        - name: ssl-certs
          mountPath: /etc/nginx/ssl
          readOnly: true
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: seovalidator-storage-pvc
      - name: ssl-certs
        secret:
          secretName: seovalidator-ssl-certs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seovalidator-horizon
  namespace: seovalidator
  labels:
    app: seovalidator
    component: horizon
spec:
  replicas: 2
  selector:
    matchLabels:
      app: seovalidator
      component: horizon
  template:
    metadata:
      labels:
        app: seovalidator
        component: horizon
    spec:
      containers:
      - name: horizon
        image: seovalidator:latest
        command: ["php", "artisan", "horizon"]
        envFrom:
        - configMapRef:
            name: seovalidator-config
        - secretRef:
            name: seovalidator-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - php
            - artisan
            - horizon:status
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        volumeMounts:
        - name: storage
          mountPath: /var/www/html/storage
        - name: logs
          mountPath: /var/www/html/storage/logs
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: seovalidator-storage-pvc
      - name: logs
        persistentVolumeClaim:
          claimName: seovalidator-logs-pvc